def setLogLevel(levelname: str | None = None) -> None: ...
def info(msg: str, *args: object) -> None: ...
def output(msg: str, *args: object) -> None: ...
def warn(msg: str, *args: object) -> None: ...
def warning(msg: str, *args: object) -> None: ...
def error(msg: str, *args: object) -> None: ...
def debug(msg: str, *args: object) -> None: ...
