from typing import Any

class Node:
    name: str
    def cmd(self, *args: Any, **kwargs: Any) -> str: ...
    def intfList(self) -> list[Any]: ...

class Host(Node): ...
class CPULimitedHost(Host): ...

class Switch(Node): ...

class Controller(Node):
    def __init__(self, name: str, **kwargs: Any) -> None: ...

class OVSController(Controller): ...
class RemoteController(Controller):
    def __init__(
        self, name: str, ip: str = "127.0.0.1", port: int | None = None, **kwargs: Any
    ) -> None: ...
