from typing import Any

class Node:
    name: str
    def __init__(self, name: str, inNamespace: bool = ..., **params: Any) -> None: ...
    def cmd(self, *args: Any, **kwargs: Any) -> str: ...
    def config(
        self,
        mac: str | None = None,
        ip: str | None = None,
        defaultRoute: str | None = None,
        lo: str = "up",
        **params: Any,
    ) -> dict[str, Any]: ...
    def terminate(self) -> None: ...
    def intfList(self) -> list[Any]: ...

class Host(Node): ...
class CPULimitedHost(Host): ...

class Switch(Node): ...
class OVSSwitch(Switch):
    def __init__(self, name: str, **params: Any) -> None: ...

class Controller(Node):
    def __init__(self, name: str, **kwargs: Any) -> None: ...

class OVSController(Controller): ...
class RemoteController(Controller):
    def __init__(
        self, name: str, ip: str = "127.0.0.1", port: int | None = None, **kwargs: Any
    ) -> None: ...

def DefaultController(name: str, **kwargs: Any) -> Controller: ...
