from typing import Any

class Topo:
    def __init__(self, *args: Any, **params: Any) -> None: ...
    def build(self, *args: Any, **params: Any) -> None: ...
    def addNode(self, name: str, **opts: Any) -> str: ...
    def addHost(self, name: str, **opts: Any) -> str: ...
    def addSwitch(self, name: str, **opts: Any) -> str: ...
    def addLink(
        self,
        node1: str,
        node2: str,
        port1: int | None = None,
        port2: int | None = None,
        key: str | None = None,
        **opts: Any,
    ) -> Any: ...
    def nodes(self, sort: bool = True) -> list[str]: ...
    def hosts(self) -> list[str]: ...
    def switches(self) -> list[str]: ...
