from typing import Any

from .iptopo import IPTopo


class IPNet:
    def __init__(self, topo: IPTopo | None = None, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, name: str) -> Any: ...
    def start(self) -> None: ...
    def cli(self) -> None: ...
    def stop(self) -> None: ...
