from typing import Any

from .ipnet import IPNet


class IPTopo:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def build(self, *args: Any, **kwargs: Any) -> None: ...
    def post_build(self, net: IPNet) -> None: ...
    def addRouter(self, name: str, **kwargs: Any) -> str: ...
    def addHost(self, name: str, **kwargs: Any) -> str: ...
    def addLink(self, node1: str, node2: str, *args: Any, **kwargs: Any) -> None: ...
    def addDaemon(self, node: str, daemon: Any, **kwargs: Any) -> None: ...
